name: deal_app
description: "A new Flutter project."

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.2.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter



  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  # db
  sqflite: ^2.2.8+2
  path_provider: ^2.1.1
  path: ^1.8.3
  # images
  image_picker: ^0.8.6
  #splash 
  another_flutter_splash_screen: ^1.2.0
  #snack bar
  delightful_toast: ^1.1.0
  #info views
  animated_introduction: ^1.0.4


  flutter_lints: ^2.0.0



flutter:


  uses-material-design: true

 
  assets:
    - assets/
  


